language: node_js
node_js:
  - '7'
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database realtime;' -U postgres
  - npm run init
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
